# App Engine configuration (alternative deployment option)
runtime: python310

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  API_TITLE: "Marketing Campaign Response Prediction API"
  API_VERSION: "1.0.0"

# Resource allocation
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

# Network settings
vpc_access_connector:
  name: "projects/PROJECT_ID/locations/us-central1/connectors/default-connector"

# Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300